vyos_build_repo: "https://github.com/vyos/vyos-build.git"
vyos_build_ref: "18a550b7f857bdea5eb84e1553664bd203173566"
vyos_build_dir: "/opt/vyos-build"
vyos_build_version: "2026.09.09-0029-rolling"

vyos_architecture: "amd64"
vyos_build_flavor: "proxmox"
vyos_build_by: "ansible@unicamp"

vyos_ip_cidr: "10.10.10.1/24"
vyos_gateway: "10.10.10.254"
vyos_eth0_mac: "02:00:00:00:10:01"
vyos_eth1_mac: "02:00:00:00:10:02"

vyos_seed_dir: "{{ vyos_build_dir }}/seed"
vyos_seed_iso: "{{ vyos_build_dir }}/seed.iso"
vyos_seed_iso_name: "vyos-seed.iso"
vyos_seed_iso_target: "/var/lib/vz/template/iso/{{ vyos_seed_iso_name }}"

vyos_target_image: "/var/lib/vz/template/iso/vyos-{{ vyos_build_version }}-{{ vyos_architecture }}-proxmox.img"
vyos_builder_image: "vyos-build:{{ vyos_build_ref }}"
