---
users:
  - name: "Onboard Student"
    #username: "onboard.student" (optional)
    email: "onboard.student@example.com"
users_offboard:
  - username: "offboard.student"
    name: "Offboard Student"
    email: "offboard.student@example.com"
