---
- name: core | headscale | download Debian package
  ansible.builtin.get_url:
    url: "https://github.com/juanfont/headscale/releases/download/v{{ headscale_version }}/headscale_{{ headscale_version }}_linux_{{ headscale_arch }}.deb"
    dest: "/tmp/headscale.deb"
    mode: '0644'

- name: core | headscale | install Headscale package
  ansible.builtin.apt:
    deb: "/tmp/headscale.deb"
    state: present

- name: core | headscale | create Headscale directory
  ansible.builtin.file:
    path: /etc/headscale
    state: directory
    mode: '0755'

- name: core | headscale | create Let's Encrypt cache directory
  ansible.builtin.file:
    path: /var/lib/headscale/cache
    state: directory
    owner: headscale
    group: headscale
    mode: '0750'
  notify: core | headscale | restart systemd service

- name: core | headscale | fetch OIDC client secret from Kanidm
  ansible.builtin.shell: "KANIDM_PASSWORD=$(cat /root/kanidm_idm_admin_password.txt) kanidm system oauth2 show-basic-secret headscale --name idm_admin"
  delegate_to: kanidm
  register: headscale_oidc_secret_raw
  changed_when: false
  no_log: true

- name: core | headscale | deploy Headscale config.yaml
  ansible.builtin.template:
    dest: /etc/headscale/config.yaml
    src: config.yaml.j2
    owner: headscale
    group: headscale
    mode: '0644'
  notify: core | headscale | restart systemd service

- name: core | headscale | map public domain to caddy to bypass Hairpin NAT
  ansible.builtin.lineinfile:
    path: /etc/hosts
    # routes internal requests through Caddy (10.10.20.4) to get valid TLS
    line: "{{ ip_caddy_reverseproxy }} andira.lbic.fee.unicamp.br"
    state: present

- name: core | headscale | enable and start systemd service
  ansible.builtin.systemd:
    name: headscale
    state: started
    enabled: true
