---
- name: core | headscale | download Debian package
  ansible.builtin.get_url:
    url: "https://github.com/juanfont/headscale/releases/download/v{{ headscale_version }}/headscale_{{ headscale_version }}_linux_amd64.deb"
    dest: "/tmp/headscale.deb"
    mode: '0644'

- name: core | headscale | install Headscale package
  ansible.builtin.apt:
    deb: "/tmp/headscale.deb"
    state: present

- name: core | headscale | create Headscale directory
  ansible.builtin.file:
    path: /etc/headscale
    state: directory
    mode: '0755'

- name: core | headscale | deploy Headscale config.yaml
  ansible.builtin.copy:
    dest: /etc/headscale/config.yaml
    src: headscale/config.yaml
    owner: headscale
    group: headscale
    mode: '0644'
  notify: core | headscale | restart systemd service

- name: core | headscale | enable and start systemd service
  ansible.builtin.systemd:
    name: headscale
    state: started
    enabled: true
