- name: core | headscale | enable IPv4 forwarding for subnet routing
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: core | headscale | check if Tailscale is installed
  ansible.builtin.command: which tailscale
  register: tailscale_installed
  changed_when: false
  failed_when: false

- name: core | headscale | ensure curl and ca-certificates are installed
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
    state: present
    update_cache: yes
  when: tailscale_installed.rc != 0

- name: core | headscale | download Tailscale install script
  ansible.builtin.get_url:
    url: https://tailscale.com/install.sh
    dest: /tmp/install_tailscale.sh
    mode: '0700'
  when: tailscale_installed.rc != 0
