---
- name: core | headscale onboarding | load student directory variables
  ansible.builtin.include_vars:
    file: users.yml

- name: core | headscale onboarding | create user namespaces in Headscale
  ansible.builtin.command: "headscale users create {{ item.username }}"
  loop: "{{ users }}"
  register: user_creation
  failed_when:
    - user_creation.rc != 0
    - "'UNIQUE constraint failed' not in user_creation.stderr"
    - "'already exists' not in user_creation.stderr" # kept for backwards compatibility
  changed_when: user_creation.rc == 0
