---
- name: core | headscale onboarding | load student directory variables
  ansible.builtin.include_vars:
    file: users.yml

- name: core | headscale onboarding | create user namespaces in Headscale
  ansible.builtin.command: "headscale users create {{ item.username }}"
  loop: "{{ users }}"
  register: user_creation
  failed_when:
    - user_creation.rc != 0
    - "'UNIQUE constraint failed' not in user_creation.stderr"
    - "'already exists' not in user_creation.stderr" # kept for backwards compatibility
  changed_when: user_creation.rc == 0

- name: core | headscale onboarding | fetch registered devices
  ansible.builtin.command: "headscale nodes list --output json"
  register: all_nodes
  changed_when: false

- name: core | headscale onboarding | fetch registered users to get IDs
  ansible.builtin.command: "headscale users list --output json"
  register: registered_users
  changed_when: false

- name: core | headscale onboarding | fetch all existing pre-auth keys
  ansible.builtin.command: "headscale preauthkeys list --output json"
  register: all_keys
  changed_when: false

- name: core | headscale onboarding | generate pre-auth keys for users without active keys
  ansible.builtin.command: "headscale preauthkeys create --user {{ (registered_users.stdout | from_json | selectattr('name', 'equalto', item.username) | first).id }} --expiration 24h"
  loop: "{{ users }}"
  when:
    # check 1: user has no registered devices
    - (all_nodes.stdout | default('[]', true) | from_json | selectattr('user.name', 'equalto', item.username) | list | length) == 0
    # check 2: user has no unused pre-auth keys (defaults to false if the 'used' JSON key is omitted)
    - (all_keys.stdout | default('[]', true) | from_json | selectattr('user.name', 'equalto', item.username) | map(attribute='used', default=false) | reject | list | length) == 0
  register: generated_keys
