---
- name: core | kanidm headscale | create Headscale OIDC application
  ansible.builtin.command: >
    kanidm system oauth2 create headscale "Headscale VPN"
    {{ kanidm_headscale_oidc_callback }} --name idm_admin
  register: kanidm_oauth2_create
  changed_when:
    - kanidm_oauth2_create.rc == 0
    - "'already' not in kanidm_oauth2_create.stdout | lower"
    - "'already' not in kanidm_oauth2_create.stderr | lower"
  failed_when:
    - kanidm_oauth2_create.rc != 0
    - "'already exists' not in kanidm_oauth2_create.stderr"
    - "'409 Conflict' not in kanidm_oauth2_create.stderr"

- name: core | kanidm headscale | create headscale_users group
  ansible.builtin.command: kanidm group create headscale_users --name idm_admin
  register: kanidm_group_create
  changed_when:
    - kanidm_group_create.rc == 0
    - "'409' not in kanidm_group_create.stderr"
    - "'409' not in kanidm_group_create.stdout"
    - "'already' not in kanidm_group_create.stderr | lower"
    - "'already' not in kanidm_group_create.stdout | lower"
  failed_when:
    - kanidm_group_create.rc != 0
    - "'already exists' not in kanidm_group_create.stderr | lower"
    - "'already exists' not in kanidm_group_create.stdout | lower"
    - "'409' not in kanidm_group_create.stderr"
    - "'409' not in kanidm_group_create.stdout"
