---
- name: core | kanidm setup | install repository and cryptography dependencies
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
      - python3-cryptography
    state: present
    update_cache: yes

- name: core | kanidm setup | download Kanidm GPG key
  ansible.builtin.get_url:
    url: https://kanidm.github.io/kanidm_ppa/kanidm_ppa.asc
    dest: /etc/apt/trusted.gpg.d/kanidm_ppa.asc
    mode: '0644'

- name: core | kanidm setup | add Kanidm APT repository (deb822 format)
  ansible.builtin.deb822_repository:
    name: kanidm
    types: deb
    architectures: amd64
    uris: https://kanidm.github.io/kanidm_ppa
    suites: "{{ ansible_facts['distribution_release'] | lower }}"
    components: stable
    signed_by: /etc/apt/trusted.gpg.d/kanidm_ppa.asc
    state: present
