---
- name: core | kanidm unix backend | create a read-only service account for workstations
  ansible.builtin.command: kanidm service-account create unix-clients "Unix Clients Service Account" idm_admin --name idm_admin
  register: kanidm_sa_create
  changed_when:
    - kanidm_sa_create.rc == 0
    - "'409' not in kanidm_sa_create.stderr"
    - "'409' not in kanidm_sa_create.stdout"
    - "'already' not in kanidm_sa_create.stderr | lower"
    - "'already' not in kanidm_sa_create.stdout | lower"
  failed_when:
    - kanidm_sa_create.rc != 0
    - "'already exists' not in kanidm_sa_create.stderr | lower"
    - "'already exists' not in kanidm_sa_create.stdout | lower"
    - "'409' not in kanidm_sa_create.stderr"
    - "'409' not in kanidm_sa_create.stdout"

- name: core | kanidm unix backend | enable POSIX access for workstation service account
  ansible.builtin.command: kanidm service-account posix set unix-clients --name idm_admin
  register: kanidm_sa_posix
  changed_when:
    - kanidm_sa_posix.rc == 0
    - "'409' not in kanidm_sa_posix.stderr"
    - "'409' not in kanidm_sa_posix.stdout"
    - "'already' not in kanidm_sa_posix.stderr | lower"
    - "'already' not in kanidm_sa_posix.stdout | lower"
  failed_when:
    - kanidm_sa_posix.rc != 0
    - "'already' not in kanidm_sa_posix.stderr | lower"
    - "'already' not in kanidm_sa_posix.stdout | lower"
    - "'409' not in kanidm_sa_posix.stderr"
    - "'409' not in kanidm_sa_posix.stdout"

- name: core | kanidm unix backend | check unix authentication read membership
  ansible.builtin.command:
    cmd: kanidm group list-members idm_unix_authentication_read --name idm_admin
  register: kanidm_unix_auth_read_members
  changed_when: false

- name: core | kanidm unix backend | grant unix authentication read permission
  ansible.builtin.command:
    cmd: kanidm group add-members idm_unix_authentication_read unix-clients --name idm_admin
  when: "'unix-clients' not in kanidm_unix_auth_read_members.stdout"
  changed_when: true

- name: core | kanidm unix backend | check existing workstation service account tokens
  ansible.builtin.command: kanidm service-account api-token status unix-clients --name idm_admin
  register: kanidm_sa_tokens
  changed_when: false

- name: core | kanidm | generate shared token for workstations
  ansible.builtin.command: kanidm service-account api-token generate unix-clients shared-token --name idm_admin
  register: kanidm_sa_token_generate
  when: "'shared-token' not in kanidm_sa_tokens.stdout"
  changed_when: true
  no_log: true

- name: core | kanidm | save newly generated token to root directory
  ansible.builtin.copy:
    content: "{{ kanidm_sa_token_generate.stdout_lines[-1] }}"
    dest: /root/kanidm_unixd_token.txt
    mode: '0600'
  when: kanidm_sa_token_generate.changed
  no_log: true
