- name: vyos | build image | check if VyOS image already exists
  ansible.builtin.stat:
    path: "{{ vyos_target_image }}"
  register: vyos_target_image_exists

- name: vyos | build image | build and deploy image
  when: not vyos_target_image_exists.stat.exists
  block:

    - name: vyos | build image | install podman and git
      ansible.builtin.apt:
        name:
          - podman
          - git
        state: present
        update_cache: true
