---

- name: vyos | routing | configure interfaces, DNS, and NAT
  vyos.vyos.vyos_config:
    lines:
      - set interfaces ethernet eth0 description 'WAN-TRANSIT'
      - set interfaces ethernet eth1 description 'LAN-TRUNK'
      - set interfaces ethernet eth1 vif 20 address '{{ ip_vyos_router_lan }}/24'
      - set interfaces ethernet eth1 vif 20 description 'INFRA-VLAN'
      - set system name-server '1.1.1.1'
      - set protocols static route 0.0.0.0/0 next-hop '{{ ip_proxmox_hypervisor }}'
  notify: vyos | routing | save configuration
