---

- name: vyos | routing | configure interfaces, DNS, and NAT
  vyos.vyos.vyos_config:
    lines:
      - set interfaces ethernet eth0 description 'WAN-TRANSIT'
      - set interfaces ethernet eth1 description 'LAN-TRUNK'
      - set interfaces ethernet eth1 vif 20 address '10.10.20.1/24'
      - set interfaces ethernet eth1 vif 20 description 'INFRA-VLAN'
      - set system name-server '1.1.1.1'
      - set nat source rule 100 outbound-interface name 'eth0'
      - set nat source rule 100 source address '10.10.0.0/16'
      - set nat source rule 100 translation address 'masquerade'
  register: vyos_config_result

- name: vyos | routing | save configuration
  vyos.vyos.vyos_command:
    commands:
      - configure
      - save
      - exit
  changed_when: true
  when: vyos_config_result.changed
