lbic:
  vars:
    ansible_user: ansible
  children:

    lbic_experiment:
      hosts:
        paubrasil:    # xxx.xx.xx.179

    lbic_workstation:
      hosts:
        #andira:      # xxx.xxx.xxx.162
        aroeira:      # xxx.xxx.xxx.163
        baoba:        # xxx.xxx.xxx.164
        barauna:      # xxx.xxx.xxx.165
        cajazeira:    # xxx.xxx.xxx.166
        cambuci:      # xxx.xxx.xxx.167
        castanheiro:  # xxx.xxx.xxx.168
        #catuaba:     # xxx.xxx.xxx.169
        cedro:        # xxx.xxx.xxx.170
        embira:       # xxx.xxx.xxx.171
        gameleira:    # xxx.xxx.xxx.172
        imburana:     # xxx.xxx.xxx.173
        ipe:          # xxx.xxx.xxx.174
        jacaranda:    # xxx.xxx.xxx.175
        jatoba:       # xxx.xxx.xxx.176
        jequitiba:    # xxx.xxx.xxx.177
        mogno:        # xxx.xxx.xxx.178
        #paubrasil:   # xxx.xxx.xxx.179
        peroba:       # xxx.xxx.xxx.180
        seringueira:  # xxx.xxx.xxx.181
        umbu:         # xxx.xxx.xxx.182
        canabis:      # xxx.xxx.xxx.183

    lbic_server:
      hosts:

        andira:
          ansible_host: andira
          ansible_user: root

        proxmox:
          ansible_host: andira
          ansible_user: root

        vyos:
          ansible_host: 10.10.10.1
          ansible_user: vyos
          ansible_connection: ansible.netcommon.network_cli
          ansible_network_os: vyos.vyos.vyos
          ansible_network_cli_ssh_type: libssh
          ansible_libssh_proxy_command: 'ssh -W %h:%p -q root@andira'

        headscale:
          ansible_host: 10.10.20.2
          ansible_user: root
          ansible_ssh_common_args: '-J root@andira'
