---
- name: core | proxmox | configure vmbr0 port forwarding for Headscale
  ansible.builtin.blockinfile:
    path: /etc/network/interfaces
    insertbefore: '^source /etc/network/interfaces\.d/.*'
    marker: "        # {mark} ANSIBLE MANAGED BLOCK: VMBR0 HEADSCALE DNAT"
    block: "{{ lookup('file', 'vmbr0_headscale.txt') }}"
  register: network_config_vmbr0

- name: core | proxmox | configure vmbr1 NAT bridge
  ansible.builtin.blockinfile:
    path: /etc/network/interfaces
    marker: "# {mark} ANSIBLE MANAGED BLOCK: VMBR1 NAT"
    block: "{{ lookup('file', 'vmbr1.txt') }}"
  register: network_config_vmbr1

- name: core | proxmox | bring up vmbr1 interface
  ansible.builtin.command: ifup vmbr1
  when: network_config_vmbr1.changed

- name: core | proxmox | configure vmbr2 VLAN-aware trunk
  ansible.builtin.blockinfile:
    path: /etc/network/interfaces
    marker: "# {mark} ANSIBLE MANAGED BLOCK: VMBR2 TRUNK"
    block: "{{ lookup('file', 'vmbr2.txt') }}"
  register: network_config_vmbr2

- name: core | proxmox | bring up vmbr2 interface
  ansible.builtin.command: ifup vmbr2
  when: network_config_vmbr2.changed

- name: core | proxmox | configure DNS resolution
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
