---
- name: core | proxmox | initialize OpenTofu
  ansible.builtin.command:
    cmd: make init TOFU_ARGS="-input=false"
    chdir: /home/rafael/git/homelab/tofu
  delegate_to: localhost
  changed_when: false
