#+TITLE: OpenTofu Infrastructure
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args
#+DESCRIPTION: OpenTofu config file for provisioning LXC containers and VMs in Proxmox
#+STARTUP: showeverything
#+auto_tangle: t

* Table of Contents :toc:
- [[#global-configuration][Global Configuration]]
  - [[#terraform][Terraform]]
  - [[#providers][Providers]]
  - [[#variables][Variables]]
- [[#core][Core]]
  - [[#vyos][VyOS]]
  - [[#headscale][Headscale]]

* Global Configuration
:PROPERTIES:
:header-args+: :tangle main.tf
:END:
** Terraform
#+begin_src tofu
terraform {
#+end_src
*** Required Providers
#+begin_src tofu
  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "~> 0.112.0"
    }
  }
#+end_src
*** Client-Side State Encryption
#+begin_src tofu
  encryption {
    key_provider "pbkdf2" "mykey" {
      passphrase = var.tofu_state_passphrase
    }
    method "aes_gcm" "mymethod" {
      keys = key_provider.pbkdf2.mykey
    }
    state {
      method = method.aes_gcm.mymethod
      enforced = true
    }
    plan {
      method = method.aes_gcm.mymethod
      enforced = true
    }
  }
#+end_src
*** EoS
#+begin_src tofu
}
#+end_src
** Providers
*** Proxmox
Provider setup: how OpenTofu authenticates to Proxmox.
Authentication tokens should be passed via env var =PROXMOX_VE_API_TOKEN= in the formatted as =user@realm!tokenid=secret-uuid=.
#+begin_src tofu
provider "proxmox" {
  endpoint = "https://andira.lbic.fee.unicamp.br:8006/"
  # Set to true if using self-signed certificates on the Proxmox host
  insecure = true

  ssh {
    agent    = false
    username = "root"
    private_key = file("~/.ssh/id_ed25519")
  }
}
#+end_src
** Variables
*** SSH Public Keys
**** Laptop IPF
#+begin_src tofu
variable "ssh_key_laptop" {
  type        = string
  description = "The SSH public key for the IPF laptop"
}
#+end_src
**** Desktop Catuaba
#+begin_src tofu
variable "ssh_key_desktop" {
  type        = string
  description = "The SSH public key for the Catuaba desktop"
}
#+end_src
*** Tofu State Passphrase
#+begin_src tofu
variable "tofu_state_passphrase" {
  type        = string
  description = "Passphrase for OpenTofu client-side state encryption"
  sensitive   = true
}
#+end_src
* Core
** VyOS :noexport_1:
:PROPERTIES:
:header-args+: :tangle vyos.tf
:END:
Core Router.
*** Variables
**** Network IP
#+begin_src tofu
variable "vyos_ip_cidr" {
  type        = string
  description = "The management IP address and CIDR for the VyOS router"
  default     = "10.10.10.1/24"
}
#+end_src
**** Network Gateway
#+begin_src tofu
variable "vyos_gateway" {
  type        = string
  description = "The default gateway for the VyOS router (usually the university network gateway)"
  default     = "10.10.10.254"
}
#+end_src
**** Local
#+begin_src tofu
locals {
  # read the Ansible variables
  vyos_vars = yamldecode(file("${path.module}/../ansible/roles/vyos/vars/main.yml"))
#+end_src
*****  Image build filename
#+begin_src tofu
  # replace the architecture tag
  path_step1 = replace(local.vyos_vars.vyos_target_image, "{{ vyos_architecture }}", local.vyos_vars.vyos_architecture)
  # replace the version tag
  path_step2 = replace(local.path_step1, "{{ vyos_build_version }}", local.vyos_vars.vyos_build_version)
  # extract the final filename
  vyos_image_name = basename(local.path_step2)
#+end_src
***** EoS
#+begin_src tofu
}
#+end_src
*** Virtual Machine
This block provisions the VyOS 1.4 router VM. It attaches to the external network (=vmbr1=) and the internal VLAN trunk (=vmbr2=).
**** Resource
#+begin_src tofu
resource "proxmox_virtual_environment_vm" "vyos" {
  name        = "vyos"
  description = "VyOS Core Router"
  node_name   = "andira"
  vm_id       = 201
  tags        = ["core", "router", "vyos"]

  # router must boot before LXCs and Kubernetes
  started = true
  on_boot = true
  startup {
    order      = 1
    up_delay   = 10
  }

  # communicates with the injected qemu-guest-agent
  agent {
    enabled = true
  }
  # eth0: WAN Interface
  # Transit Network (facing the physical network)
  network_device {
    bridge = "vmbr1"
  }
  # eth1: LAN Interface
  # Internal Trunk (VLAN Trunk for internal lab networks)
  network_device {
    bridge = "vmbr2"
  }
#+end_src
**** Disk
#+begin_src tofu
  disk {
    datastore_id = "local-lvm"
    # ensure the VyOS image has QCOW2 support
    file_id      = "local:iso/${local.vyos_image_name}"
    interface    = "virtio0"
    file_format  = "raw"
    size         = 10
  }
#+end_src
**** Initialization
#+begin_src tofu
  # Cloud-Init Bootstrap
  initialization {
#+end_src
***** SSH Keys
#+begin_src tofu
    user_account {
      username = "vyos"
      keys     = [
        var.ssh_key_laptop,
        var.ssh_key_desktop
      ]
    }
#+end_src
***** Network
#+begin_src tofu
    ip_config {
      ipv4 {
        address = var.vyos_ip_cidr
        gateway = var.vyos_gateway
      }
    }
#+end_src
***** EoS
#+begin_src tofu
}
#+end_src
**** EoS
#+begin_src tofu
}
#+end_src
** Headscale :noexport_1:
:PROPERTIES:
:header-args+: :tangle headscale.tf
:END:
VPN.
*** Variables
**** Network IP
#+begin_src tofu
variable "headscale_ip_cidr" {
  type        = string
  description = "The IP address and CIDR for the Headscale LXC"
  default     = "10.10.20.2/24"
}
#+end_src
**** Network Gateway
#+begin_src tofu
variable "headscale_gateway" {
  type        = string
  description = "The default gateway for the Headscale LXC"
  default     = "10.10.20.1"
}
#+end_src
*** LXC Container
This block provisions the Debian 13 (Trixie) container on the internal bridge (=vmbr2=).
**** Resource
#+begin_src tofu
resource "proxmox_virtual_environment_container" "headscale" {
  description = "Headscale VPN Controller"
  tags        = ["core", "vpn", "headscale"]
  node_name = "andira"
  vm_id     = 202

  # ensure unprivileged mode
  unprivileged = true

  # autostart
  start_on_boot = true

  # enable nesting
  features {
    nesting = true
  }

  # ensure the container starts early in the boot sequence (lower = earlier)
  startup {
    order      = 10
    up_delay   = 5
    down_delay = 5
  }
#+end_src
**** OS
#+begin_src tofu
  operating_system {
    template_file_id = "local:vztmpl/debian-13-standard_13.6-1_amd64.tar.zst"
    type             = "debian"
  }
#+end_src
**** CPU
#+begin_src tofu
  cpu {
    cores = 1
  }
#+end_src
**** Memory
#+begin_src tofu
  memory {
    dedicated = 512
    swap      = 0
  }
#+end_src
**** Disk
#+begin_src tofu
  disk {
    datastore_id = "local-lvm"
    size         = 4
  }
#+end_src
**** Network
#+begin_src tofu
  network_interface {
    name   = "eth0"
    bridge = "vmbr2"
    vlan_id = 20  # "Infra" VLAN
  }
#+end_src
**** Initialization
#+begin_src tofu
  initialization {
    hostname = "headscale"
#+end_src
***** DNS
#+begin_src tofu :tangle no
    dns {
      servers = ["10.10.20.x", "10.10.20.y"]  # DNS-1, DNS-2
    }
#+end_src
***** IP
#+begin_src tofu
    ip_config {
      ipv4 {
        address = var.headscale_ip_cidr
        gateway = var.headscale_gateway
      }
    }
#+end_src
***** SSH Keys
#+begin_src tofu
    user_account {
      keys = [
        var.ssh_key_laptop,
        var.ssh_key_desktop
      ]
    }
#+end_src
***** EoS
#+begin_src tofu
}
#+end_src
**** EoS
#+begin_src tofu
}
#+end_src
