---
- name: Configure Workstations
  hosts: lbic_workstation
  become: yes
  tasks:
    - name: workstation | configure regular workstations
      ansible.builtin.import_role:
        name: lab_workstation
