---
- name: Configure Experiments Server
  hosts: lbic_experiments
  become: yes
  tasks:
    - name: experiments | configure experiments server
      ansible.builtin.import_role:
        name: lab_experiments
