---
- name: headscale | onboarding | onboard new VPN user
  hosts: headscale
  gather_facts: false
  vars:
    # fails if "student" is not provided via -e flag
    target_user: "{{ student | mandatory }}"
  tasks:

    - name: headscale | onboarding | ensure user exists in Headscale
      ansible.builtin.command: "headscale users create {{ target_user }}"
      register: user_creation
      failed_when:
        - user_creation.rc != 0
        - "'already exists' not in user_creation.stderr"
        - "'UNIQUE constraint failed' not in user_creation.stderr"
      changed_when: user_creation.rc == 0
