#+TITLE: Ansible Playbooks
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args
#+STARTUP: showeverything
#+auto_tangle: t

* Table of Contents :toc_2:
- [[#server-infrastructure][Server Infrastructure]]
  - [[#proxmox-hypervisor][Proxmox Hypervisor]]
  - [[#opentofu][OpenTofu]]
  - [[#vyos-router][VyOS Router]]
  - [[#technitium-dns][Technitium DNS]]
  - [[#caddy-reverse-proxy][Caddy Reverse Proxy]]
  - [[#kanidm-iam][Kanidm IAM]]
  - [[#headscale-vpn][Headscale VPN]]
- [[#experiments-server][Experiments Server]]
- [[#workstations][Workstations]]
- [[#user-onboard][User Onboard]]
- [[#workstation-onboard][Workstation Onboard]]
- [[#offboarding-user][Offboarding User]]

* Server Infrastructure
:PROPERTIES:
:header-args:yaml+: :tangle deploy_infrastructure.yml
:END:
This is the master orchestration file. It maps host groups from the inventory to specific task files within the =lbic= role.
#+begin_src yaml
---
#+end_src
** Secure Variables (Vault) :noexport:
Secrets are stored in an encrypted Ansible vault and should not be stored in plaintext. To edit the vault, run:
#+begin_src sh
ansible-vault edit group_vars/all/vault.yml
#+end_src
** Proxmox Hypervisor
Runs against the physical host to configure bridges, networking, and foundational time synchronization.
#+begin_src yaml :padline no
- name: Configure Proxmox Hypervisor
  hosts: proxmox
  become: yes
  tasks:
    - name: core | proxmox | configure hypervisor foundation
      ansible.builtin.import_role:
        name: proxmox

    - name: core | ntp | configure time synchronization
      ansible.builtin.import_role:
        name: chrony

    - name: core | vyos | build VyOS image on Proxmox server
      ansible.builtin.import_role:
        name: vyos
        tasks_from: build_image.yml
#+end_src
** OpenTofu
Runs against the Proxmox server to provision the LXC containers and Virtual Machines.
#+begin_src yaml
- name: Provision LXC containers and VMs
  hosts: proxmox
  become: no
  tasks:
    - name: core | infrastructure | provision LXC containers and VMs
      ansible.builtin.import_role:
        name: proxmox
        tasks_from: provision.yml
#+end_src
** VyOS Router
Runs against the core router to configure VLANs and NAT via the network CLI.
#+begin_src yaml
- name: Configure VyOS Core Router
  hosts: vyos
  gather_facts: no
  tasks:
    - name: core | vyos | wait for boot and configure router
      ansible.builtin.import_role:
        name: vyos
#+end_src
** Technitium DNS
Runs against the DNS LXCs to install and configure Technitium.
#+begin_src yaml
- name: Configure Technitium DNS Servers
  hosts: dns-*
  become: yes
  tasks:
    - name: core | dns | deploy authoritative and recursive DNS
      ansible.builtin.import_role:
        name: technitium
#+end_src
** Caddy Reverse Proxy
Runs against the Caddy LXC container to manage automated Let's Encrypt TLS certificates and edge routing.
#+begin_src yaml
- name: Configure Caddy Reverse Proxy
  hosts: caddy
  become: yes
  tasks:
    - name: core | caddy | deploy reverse proxy and tls
      ansible.builtin.import_role:
        name: caddy
#+end_src
** Kanidm IAM
Runs against the Kanidm LXC container to deploy the directory database, administrative recovery, and OIDC clients.
#+begin_src yaml
- name: Configure Kanidm IAM Server
  hosts: kanidm
  become: yes
  tasks:
    - name: core | kanidm | deploy server and headscale integration
      ansible.builtin.import_role:
        name: kanidm
#+end_src
** Headscale VPN
Runs against the LXC container to install and configure the VPN controller.
#+begin_src yaml
- name: Configure Headscale VPN Controller
  hosts: headscale
  become: yes
  tasks:
    - name: core | headscale | deploy VPN controller and subnet router
      ansible.builtin.import_role:
        name: headscale
#+end_src
* Experiments Server :noexport_1:
:PROPERTIES:
:header-args:yaml+: :tangle deploy_experiments.yml
:END:
Runs against physical shared lab servers used for computational experiments in CPU/GPU with Podman containers and Python in Mamba environments.
#+begin_src yaml
---
#+end_src
** Configure Experiments Server
#+begin_src yaml :padline no
- name: Configure Experiments Server
  hosts: lbic_experiments
  become: yes
  tasks:
    - name: experiments | configure experiments server
      ansible.builtin.import_role:
        name: lab_experiments
#+end_src
* Workstations :noexport_1:
:PROPERTIES:
:header-args:yaml+: :tangle deploy_workstations.yml
:END:
Runs against physical lab workstations to install packages, hook PAM/NSS into Kanidm central identity, and enable SSH key distribution.
#+begin_src yaml
---
#+end_src
** Configure Workstations
#+begin_src yaml :padline no
- name: Configure Workstations
  hosts: lbic_workstation
  become: yes
  tasks:
    - name: workstation | configure regular workstations
      ansible.builtin.import_role:
        name: lab_workstation
#+end_src
* User Onboard :noexport_1:
:PROPERTIES:
:header-args+: :tangle tasks/user_onboard.yml
:END:
#+begin_src yaml :tangle ops_user_onboard.yml
---
- name: Onboard and Manage LBiC Students
  hosts: kanidm
  tasks:
    - name: Import user onboarding tasks
      ansible.builtin.import_tasks: tasks/user_onboard.yml
#+end_src
** Kanidm CLI Authentication
#+begin_src yaml
---
- name: ops | kanidm users | authenticate CLI as idm_admin
  ansible.builtin.shell: "KANIDM_PASSWORD=$(cat /root/kanidm_idm_admin_password.txt) kanidm login --name idm_admin"
  changed_when: false
  no_log: true
#+end_src
** Create User Accounts
#+begin_src yaml
- name: ops | users | create user accounts
  ansible.builtin.command: kanidm person create {{ item.username }} "{{ item.name }}" --name idm_admin
  loop: "{{ users }}"
  register: kanidm_user_create
  changed_when:
    - kanidm_user_create.rc == 0
    - "'already' not in kanidm_user_create.stdout | lower"
    - "'already' not in kanidm_user_create.stderr | lower"
  failed_when:
    - kanidm_user_create.rc != 0
    - "'already exists' not in kanidm_user_create.stderr"
    - "'Entry already exists' not in kanidm_user_create.stderr"
    - "'409 Conflict' not in kanidm_user_create.stderr"
#+end_src
** Generate Token For New Users
#+begin_src yaml
- name: ops | users | generate setup token for new users
  ansible.builtin.command: kanidm person credential create-reset-token {{ item.item.username }} --name idm_admin
  loop: "{{ kanidm_user_create.results }}"
  when: item.changed
  register: kanidm_setup_tokens
  changed_when: true
#+end_src
** Download Cheatsheet
#+begin_src yaml
- name: core | headscale onboarding | download latest cheatsheet PDF from GitHub
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/ito-rafael/homelab/main/docs/cheatsheet/cheatsheet.pdf"
    dest: "/tmp/cheatsheet.pdf"
    mode: '0644'
#+end_src
** Send Email With Instructions
#+begin_src yaml
- name: ops | users | send email instructions to new users
  community.general.mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ vault_smtp_user }}"
    password: "{{ vault_smtp_password }}"
    from: "LBiC Admin <{{ vault_smtp_user }}>"
    to: "{{ item.item.item.name }} <{{ item.item.item.email }}>"
    #cc:
    #  - "{{ vault_professor_name }} <{{ vault_professor_email }}>"
    #  - "{{ vault_admin_name }} <{{ vault_admin_email }}>"
    subject: "Acesso ao Cluster do LBIC (Conta e VPN)"
    subtype: html
    body: |
      <p>Olá {{ item.item.item.name.split(' ')[0] }},</p>

      <p>Sua conta para acessar os computadores do LBiC foi criada.</p>

      <ul>
        <li>
          <strong>Configuração da Senha</strong><br>
          O laboratório utiliza um sistema unificado de credenciais. Para definir sua senha pessoal ou cadastrar uma Passkey, clique no link seguro abaixo:<br><br>
          {% set parsed_token = item.stdout | regex_search('(?<=token=)[a-z0-9\-]+') %}
          <a href="https://andira.lbic.fee.unicamp.br/ui/reset?token={{ parsed_token }}"><b>Configurar Minha Conta LBiC</b></a><br><br>
          <p>Se por algum motivo o redirecionamento não funcionar, você pode usar as seguintes credenciais para criar sua conta:</p>

          <b>Link:</b> <a href="https://andira.lbic.fee.unicamp.br/ui/reset">https://andira.lbic.fee.unicamp.br/ui/reset</a><br>
          <b>Usuário:</b> {{ item.item.item.username }}<br>
          <b>Token de uso único:</b> <code>{{ parsed_token }}</code><br>
          <i>Atenção: este link de acesso expira em 24 horas.</i><br><br>
        </li>
        <li>
          <strong>Acesso à VPN (Tailscale)</strong><br>
          Após criar a sua senha, você poderá acessar a rede do laboratório de qualquer lugar. Instale o Tailscale em seu computador e execute o comando abaixo no terminal:<br><br>
          <code>sudo tailscale up --login-server https://andira.lbic.fee.unicamp.br --accept-routes</code><br><br>
          Isso abrirá uma janela no seu navegador solicitando o seu usuário ({{ item.item.item.username }}) e a senha que você acabou de criar.
        </li>
      </ul>

      <p>Aproveito para enviar em anexo um guia rápido sobre a utilização dos recursos computacionais do laboratório.</p>

      <p>Qualquer dúvida, fico à disposição.</p>
      <p>Atenciosamente,<br>{{ vault_admin_name }}</p>
    attach:
      - "/tmp/cheatsheet.pdf"
  loop: "{{ kanidm_setup_tokens.results }}"
  # send the email only to accounts that actually had a new token generated in the previous task
  when: item.changed
  # report "changed" when the email is actually dispatched
  changed_when: true
#+end_src
** Check POSIX Attributes For Users
#+begin_src yaml
- name: ops | users | inspect POSIX attributes for users
  ansible.builtin.command: kanidm person posix show --name idm_admin {{ item.username }}
  loop: "{{ users }}"
  register: kanidm_posix_state
  changed_when: false
  failed_when: false
#+end_src
** Give POSIX Attributes Users
#+begin_src yaml
- name: ops | users | give the student POSIX attributes (bash shell)
  ansible.builtin.command: kanidm person posix set {{ item.username }} --shell /bin/bash --name idm_admin
  loop: "{{ users }}"
  loop_control:
    index_var: kanidm_user_index
  when: >-
    kanidm_posix_state.results[kanidm_user_index].rc != 0 or
    'shell: /bin/bash' not in kanidm_posix_state.results[kanidm_user_index].stdout
  register: kanidm_posix
  changed_when: kanidm_posix.rc == 0
#+end_src
** Check Users Membership in Headscale Group
#+begin_src yaml
- name: ops | users | inspect Headscale VPN group membership
  ansible.builtin.command: kanidm person get {{ item.username }} --name idm_admin
  loop: "{{ users }}"
  register: kanidm_person_state
  changed_when: false
#+end_src
** Add Users to Headscale Group
#+begin_src yaml
- name: ops | users | add users to Headscale VPN group
  ansible.builtin.command: kanidm group add-members headscale_users {{ item.username }} --name idm_admin
  loop: "{{ users }}"
  loop_control:
    index_var: kanidm_user_index
  when:
    - "'memberof: headscale_users@' not in kanidm_person_state.results[kanidm_user_index].stdout"
  register: kanidm_group_add
  changed_when: kanidm_group_add.rc == 0
#+end_src
* Workstation Onboard :noexport_1:
:PROPERTIES:
:header-args+: :tangle tasks/rbac_sync.yml
:END:
#+begin_src yaml :tangle ops_rbac_sync.yml
---
- name: Onboard and Manage Workstation RBAC
  hosts: kanidm
  vars_files:
    - "../roles/kanidm/vars/main.yml"
  tasks:
    - name: Import workstation onboarding tasks
      ansible.builtin.import_tasks: tasks/rbac_sync.yml
#+end_src
** Kanidm CLI Authentication
#+begin_src yaml
---
- name: ops | workstations | authenticate CLI as idm_admin
  ansible.builtin.shell: "KANIDM_PASSWORD=$(cat /root/kanidm_idm_admin_password.txt) kanidm login --name idm_admin"
  changed_when: false
  no_log: true
#+end_src
** Configure Regular User Accounts
*** Get Workstation Users Group State
#+begin_src yaml
- name: ops | workstations | get workstation users group state
  ansible.builtin.command: "kanidm group get {{ item.hostname }}_users --name idm_admin -o json"
  loop: "{{ workstations }}"
  register: ws_users_state
  changed_when: false
  failed_when: false
#+end_src
*** Create Workstation Users Group
#+begin_src yaml
- name: ops | workstations | create workstation users group
  ansible.builtin.command: "kanidm group create {{ item.hostname }}_users --name idm_admin"
  loop: "{{ workstations }}"
  loop_control:
    index_var: idx
  vars:
    state: "{{ ws_users_state.results[idx] }}"
  # run if group doesn't exist yet
  when: "'No matching group' in state.stdout or 'not found' in state.stderr"
#+end_src
*** Grant POSIX For Workstation Users Group
#+begin_src yaml
- name: ops | workstations | enable POSIX on workstation users group
  ansible.builtin.command: "kanidm group posix set {{ item.hostname }}_users --name idm_admin"
  loop: "{{ workstations }}"
  loop_control:
    index_var: idx
  vars:
    state: "{{ ws_users_state.results[idx] }}"
    is_missing: "{{ 'No matching group' in state.stdout or 'not found' in state.stderr }}"
    group_attrs: "{{ (state.stdout | from_json).attrs if not is_missing else {} }}"
    classes: "{{ group_attrs.class | default([]) }}"
  # run if group was just created or POSIX is unset
  when: >
    is_missing or
    'posixgroup' not in classes or
    group_attrs.gidnumber is not defined
#+end_src
*** Update Workstation Users Group Members
#+begin_src yaml
- name: ops | workstations | set exact members for workstation users
  ansible.builtin.command: "kanidm group set-members {{ item.hostname }}_users {{ item.users_allowed | join(' ') }} --name idm_admin"
  loop: "{{ workstations }}"
  loop_control:
    index_var: idx
  vars:
    state: "{{ ws_users_state.results[idx] }}"
    is_missing: "{{ 'No matching group' in state.stdout or 'not found' in state.stderr }}"
    group_attrs: "{{ (state.stdout | from_json).attrs if not is_missing else {} }}"
    current_members: "{{ group_attrs.member | default([]) }}"
    expected_members: "{{ item.users_allowed | map('regex_replace', '^(.*)$', '\\1@' ~ kanidm_domain) | list }}"
  # run if group was just created, or if members list needs update
  # guardrail: run set-members only if there is at least one user to add
  when:
    - item.users_allowed is defined
    - item.users_allowed | length > 0
    - is_missing or (expected_members | sort != current_members | sort)
#+end_src
** Configure Admin User Accounts
*** Create Workstation Admins Groups
*** Get Workstation Admins Group State
#+begin_src yaml
- name: ops | workstations | create workstation admins group
  ansible.builtin.command: kanidm group create {{ item.hostname }}_admins --name idm_admin
- name: ops | workstations | get workstation admins group state
  ansible.builtin.command: "kanidm group get {{ item.hostname }}_admins --name idm_admin -o json"
  loop: "{{ workstations }}"
  register: kanidm_ws_admins_create
  changed_when:
    - kanidm_ws_admins_create.rc == 0
    - "'already' not in kanidm_ws_admins_create.stdout | lower"
    - "'already' not in kanidm_ws_admins_create.stderr | lower"
  failed_when:
    - kanidm_ws_admins_create.rc != 0
    - "'already exists' not in kanidm_ws_admins_create.stderr | lower"
    - "'409' not in kanidm_ws_admins_create.stderr"
#+end_src
*** Check POSIX For Workstation Admin Groups
#+begin_src yaml
- name: ops | workstations | check if workstation admins group has POSIX enabled
  ansible.builtin.command: kanidm group posix get {{ item.hostname }}_admins --name idm_admin
  loop: "{{ workstations }}"
  register: ws_admins_posix_get
  register: ws_admins_state
  changed_when: false
  failed_when: false
#+end_src
*** Grant POSIX For Workstation Admin Groups
#+begin_src yaml
- name: ops | workstations | enable POSIX on workstation admins group
  ansible.builtin.command: kanidm group posix set {{ item.hostname }}_admins --name idm_admin
  loop: "{{ workstations }}"
  loop_control:
    index_var: ws_index
  when:
    - ws_admins_posix_get.results[ws_index].rc != 0 or 'gidnumber' not in ws_admins_posix_get.results[ws_index].stdout | lower
  register: kanidm_ws_admins_posix
  changed_when: kanidm_ws_admins_posix.rc == 0
#+end_src
*** Enforce Group Memberships For Admin Users (RBAC)
#+begin_src yaml
- name: ops | workstations | set exact members for workstation admins
  ansible.builtin.command: "kanidm group set-members {{ item.hostname }}_admins {{ item.admin | join(' ') }} --name idm_admin"
  loop: "{{ workstations }}"
  when: item.admin is defined and item.admin | length > 0
  changed_when: true
#+end_src
* Offboarding User :noexport_1:
:PROPERTIES:
:header-args+: :tangle tasks/user_offboard.yml
:END:
#+begin_src yaml :tangle ops_user_offboard.yml
---
- name: Offboard and Remove LBiC Students
  hosts: kanidm
  tasks:
    - name: Import user offboarding tasks
      ansible.builtin.import_tasks: tasks/user_offboard.yml
#+end_src
** Kanidm CLI Authentication
#+begin_src yaml
---
- name: ops | offboard | authenticate CLI as idm_admin
  ansible.builtin.shell: "KANIDM_PASSWORD=$(cat /root/kanidm_idm_admin_password.txt) kanidm login --name idm_admin"
  changed_when: false
  no_log: true
#+end_src
** Check if Users Exist in IAM
#+begin_src yaml
- name: ops | offboard | check if user exists in Kanidm
  ansible.builtin.command: kanidm person get {{ item.username }} --name idm_admin
  loop: "{{ users_offboard | default([]) }}"
  register: kanidm_user_check
  changed_when: false
  failed_when: false
#+end_src
** Delete User Accounts from IAM
#+begin_src yaml
- name: ops | offboard | delete user accounts from Kanidm
  ansible.builtin.command: kanidm person delete {{ item.username }} --name idm_admin
  loop: "{{ users_offboard | default([]) }}"
  loop_control:
    index_var: idx
  # idempotency: only runs if the last command succeeded and username exists
  when:
    - kanidm_user_check.results[idx].rc == 0
    - item.username in kanidm_user_check.results[idx].stdout
  register: kanidm_user_delete
  changed_when: kanidm_user_delete.rc == 0
#+end_src
** Fetch Users from Headscale
#+begin_src yaml
- name: ops | offboard | fetch registered Headscale users
  ansible.builtin.command: headscale users list --output json
  delegate_to: headscale
  register: headscale_users_raw
  changed_when: false
#+end_src
** Delete Users from Headscale
#+begin_src yaml
- name: ops | offboard | delete user namespace from Headscale
  ansible.builtin.command: "headscale users destroy --name {{ item.username }}"
  loop: "{{ users_offboard | default([]) }}"
  delegate_to: headscale
  # idempotency: parse JSON and runs only if user exists
  when: (headscale_users_raw.stdout | default('[]', true) | from_json | selectattr('name', 'equalto', item.username) | list | length) > 0
  register: headscale_delete
  changed_when: true
#+end_src
** Delete Home Directories from Workstations
#+begin_src yaml
- name: ops | offboard | delete user home directories on workstations
  ansible.builtin.file:
    path: "/home/{{ item.0.username }}"
    state: absent
  # the "product" filter creates a nested loop pairing every user with every workstation
  loop: "{{ (users_offboard | default([])) | product(workstations | default([])) | list }}"
  delegate_to: "{{ item.1.hostname }}"
#+end_src
