---
- name: vyos | build vyos | build VyOS cloud-init image
  hosts: proxmox
  become: yes
  vars:
    vyos_build_dir: /opt/vyos-build
    vyos_target_image: /var/lib/vz/template/iso/vyos-1.4-cloud-init.qcow2
  tasks:

    - name: vyos | build vyos | check if VyOS image already exists
      ansible.builtin.stat:
        path: "{{ vyos_target_image }}"
      register: vyos_image_stat

    - name: vyos | build vyos | build and deploy image
      when: not vyos_image_stat.stat.exists
      block:

        - name: vyos | build vyos | install docker and git
          ansible.builtin.apt:
            name:
              - docker.io
              - git
            state: present
            update_cache: yes
