---
# load distro-specific variables
- name: load distro-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
        - "default.yml"
      # prevents crashing if absolutely no matching files exist
      skip: true
  tags: always

- ansible.builtin.import_tasks: software/packages.yml
- ansible.builtin.import_tasks: system/ssh.yml
- ansible.builtin.import_tasks: users/ansible.yml
- ansible.builtin.import_tasks: users/lbic-user.yml
