# URL clients will connect to
# (set the raw IP for Day-0 testing --> update to FQDN later)
server_url: http://10.10.20.2:8080
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 127.0.0.1:9090
# enable CLI communication
unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"

# Let's Encrypt automatic HTTPS (requires TCP 80 and 443)
tls_letsencrypt_hostname: "andira.lbic.fee.unicamp.br"
tls_letsencrypt_listen: "0.0.0.0:8080"
tls_letsencrypt_cache_dir: "/var/lib/headscale/cache"
tls_letsencrypt_challenge_type: HTTP-01

# IP ranges for Tailscale clients
prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48

# DNS
dns:
  magic_dns: true
  base_domain: lbic.internal
  nameservers:
    global:
      - 1.1.1.1
      - 8.8.8.8
  override_local_dns: true

private_key_path: /var/lib/headscale/private.key
noise:
  private_key_path: /var/lib/headscale/noise_private.key

# add Tailscale's default public DERP servers
derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default

database:
  type: sqlite
  sqlite:
    path: /var/lib/headscale/db.sqlite
