#+TITLE: Master Playbook Orchestration
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args
#+STARTUP: showeverything
#+auto_tangle: t

* Table of Contents :toc:
- [[#master-playbook][Master Playbook]]
  - [[#secure-variables-vault][Secure Variables (Vault)]]
  - [[#proxmox-hypervisor][Proxmox Hypervisor]]
  - [[#opentofu][OpenTofu]]
  - [[#vyos-router][VyOS Router]]
  - [[#technitium-dns][Technitium DNS]]
  - [[#headscale-vpn][Headscale VPN]]

* Master Playbook
:PROPERTIES:
:header-args:yaml+: :tangle site.yml
:END:
This is the master orchestration file. It maps host groups from the inventory to specific task files within the =lbic= role.
#+begin_src yaml
---
#+end_src
** Secure Variables (Vault)
Secrets are stored in an encrypted Ansible vault and should not be stored in plaintext. To edit the vault, run:
#+begin_src sh
ansible-vault edit group_vars/all/vault.yml
#+end_src
** Proxmox Hypervisor
Runs against the physical host to configure bridges, networking, and foundational time synchronization.
#+begin_src yaml :padline no
- name: Configure Proxmox Hypervisor
  hosts: proxmox
  become: yes
  tasks:
    - name: core | proxmox | configure hypervisor foundation
      ansible.builtin.import_role:
        name: proxmox

    - name: core | ntp | configure time synchronization
      ansible.builtin.import_role:
        name: chrony

    - name: core | vyos | build VyOS image on Proxmox server
      ansible.builtin.import_role:
        name: vyos
        tasks_from: build_image.yml
#+end_src
** OpenTofu
Runs against the Proxmox server to provision the LXC containers and Virtual Machines.
#+begin_src yaml
- name: Provision LXC containers and VMs
  hosts: proxmox
  become: no
  tasks:
    - name: core | infrastructure | provision LXC containers and VMs
      ansible.builtin.import_role:
        name: proxmox
        tasks_from: provision.yml
#+end_src
** VyOS Router
Runs against the core router to configure VLANs and NAT via the network CLI.
#+begin_src yaml
- name: Configure VyOS Core Router
  hosts: vyos
  gather_facts: no
  tasks:
    - name: core | vyos | wait for boot and configure router
      ansible.builtin.import_role:
        name: vyos
#+end_src
** Technitium DNS
Runs against the DNS LXCs to install and configure Technitium.
#+begin_src yaml
- name: Configure Technitium DNS Servers
  hosts: dns-*
  become: yes
  tasks:
    - name: core | dns | deploy authoritative and recursive DNS
      ansible.builtin.import_role:
        name: technitium
#+end_src
** Headscale VPN
Runs against the LXC container to install and configure the VPN controller.
#+begin_src yaml
- name: Configure Headscale VPN Controller
  hosts: headscale
  become: yes
  tasks:
    - name: core | headscale | deploy VPN controller and subnet router
      ansible.builtin.import_role:
        name: headscale
#+end_src
