#+TITLE: Ansible Role for configuring Kanidm IAM
#+AUTHOR: Rafael Ito
#+PROPERTY: header-args
#+STARTUP: showeverything
#+auto_tangle: t

* Table of Contents :toc:
- [[#tasks][Tasks]]
  - [[#main][Main]]
  - [[#timezone-configuration][Timezone Configuration]]
  - [[#server-configuration][Server Configuration]]
- [[#handlers][Handlers]]
  - [[#main-1][Main]]
- [[#vars][Vars]]
  - [[#main-2][Main]]
- [[#templates][Templates]]
  - [[#servertomlj2][server.toml.j2]]

* Tasks
** Main
#+begin_src yaml :tangle tasks/main.yml
---
- ansible.builtin.import_tasks: timezone.yml
- ansible.builtin.import_tasks: server_configuration.yml
#+end_src
** Timezone Configuration
*** Configure Timezone
#+begin_src yaml :tangle tasks/timezone.yml
---
- name: core | kanidm setup | set timezone
  community.general.timezone:
    name: "{{ timezone }}"
#+end_src
** Server Configuration
:PROPERTIES:
:header-args+: :tangle tasks/server_configuration.yml
:END:
#+begin_src yaml
---
#+end_src
*** Install Dependencies
#+begin_src yaml :padline no
- name: core | kanidm setup | install repository and cryptography dependencies
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
      - python3-cryptography
    state: present
    update_cache: yes
#+end_src
*** Configure APT Repository
**** Download Kanidm GPG key
#+begin_src yaml
- name: core | kanidm setup | download Kanidm GPG key
  ansible.builtin.get_url:
    url: https://kanidm.github.io/kanidm_ppa/kanidm_ppa.asc
    dest: /etc/apt/trusted.gpg.d/kanidm_ppa.asc
    mode: '0644'
#+end_src
**** Add Kanidm APT repository
#+begin_src yaml
- name: core | kanidm setup | add Kanidm APT repository (deb822 format)
  ansible.builtin.deb822_repository:
    name: kanidm
    types: deb
    architectures: amd64
    uris: https://kanidm.github.io/kanidm_ppa
    suites: "{{ ansible_facts['distribution_release'] | lower }}"
    components: stable
    signed_by: /etc/apt/trusted.gpg.d/kanidm_ppa.asc
    state: present
#+end_src
*** Install Kanidm server and clients
#+begin_src yaml
- name: core | kanidm setup | install Kanidm server and clients
  ansible.builtin.apt:
    name:
      - kanidm   # Kanidm Client Tools
      - kanidmd  # Kanidm Server Daemon
    state: present
    update_cache: yes
#+end_src
*** Generate TLS Certificates
Kanidm enforces strict TLS. Since we are using a self-signed chain, we generate it locally on the LXC container.
**** Create config directory
#+begin_src yaml
- name: core | kanidm setup | create kanidm config directory
  ansible.builtin.file:
    path: /etc/kanidm
    state: directory
    owner: root
    group: kanidmd
    mode: '0770'
#+end_src
**** Generate private key
#+begin_src yaml
- name: core | kanidm setup | generate private key for TLS
  community.crypto.openssl_privatekey:
    path: /etc/kanidm/key.pem
    owner: root
    group: kanidmd
    mode: '0640'
#+end_src
**** Generate CSR
#+begin_src yaml
- name: core | kanidm setup | generate CSR for Kanidm
  community.crypto.openssl_csr:
    path: /etc/kanidm/server.csr
    privatekey_path: /etc/kanidm/key.pem
    common_name: "{{ kanidm_domain }}"
    subject_alt_name:
      - "DNS:kanidm"
      - "DNS:{{ kanidm_domain }}"
      - "IP:{{ kanidm_ip }}"
#+end_src
**** Generate self-signed certificate
#+begin_src yaml
- name: core | kanidm setup | generate self-signed TLS certificate
  community.crypto.x509_certificate:
    path: /etc/kanidm/chain.pem
    privatekey_path: /etc/kanidm/key.pem
    csr_path: /etc/kanidm/server.csr
    provider: selfsigned
    owner: root
    group: kanidmd
    mode: '0640'
#+end_src
*** Configure and Start Daemon
**** Create database directory
#+begin_src yaml
- name: core | kanidm setup | create kanidmd database directory
  ansible.builtin.file:
    path: /var/lib/kanidmd
    state: directory
    owner: root
    group: kanidmd
    mode: '0750'
#+end_src
**** Deploy server.toml configuration
#+begin_src yaml
- name: core | kanidm setup | deploy server.toml configuration
  ansible.builtin.template:
    src: server.toml.j2
    dest: /etc/kanidm/server.toml
    owner: root
    group: kanidmd
    mode: '0640'
  notify: core | kanidm setup | restart systemd service
#+end_src
**** Validate server.toml configuration
#+begin_src yaml
- name: core | kanidm setup | validate server configuration
  ansible.builtin.command:
    cmd: kanidmd configtest -c /etc/kanidm/server.toml
  changed_when: false
#+end_src
**** Create systemd directory
#+begin_src yaml
- name: core | kanidm setup | create systemd service drop-in directory
  ansible.builtin.file:
    path: /etc/systemd/system/kanidmd.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
#+end_src
**** Fix systemd ExecStart
#+begin_src yaml
- name: core | kanidm setup | configure systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/kanidmd.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/kanidmd server -c /etc/kanidm/server.toml
  notify: core | kanidm setup | restart systemd service
#+end_src
**** Enable and start service
#+begin_src yaml
- name: core | kanidm setup | enable and start kanidmd service
  ansible.builtin.systemd:
    name: kanidmd
    state: started
    enabled: yes
    daemon_reload: true
#+end_src
*** Configure local Kanidm CLI
#+begin_src yaml
- name: core | kanidm setup | configure local CLI client
  ansible.builtin.copy:
    dest: /etc/kanidm/config
    owner: root
    group: root
    mode: '0644'
    content: |
      uri = "https://127.0.0.1:443"
      verify_ca = false
      verify_hostnames = false
#+end_src
*** Recover Default admin Account
Kanidm separates global configuration (admin) from user management (idm_admin).
**** Check if admin password was recovered
#+begin_src yaml
- name: core | kanidm setup | check if admin password was already recovered
  ansible.builtin.stat:
    path: /etc/kanidm/.admin_recovered
  register: admin_recovered
#+end_src
**** Recover system admin password
#+begin_src yaml
- name: core | kanidm setup | recover system admin password
  ansible.builtin.command: kanidmd recover-account -c /etc/kanidm/server.toml admin
  register: kanidm_sys_admin_recovery
  when: not admin_recovered.stat.exists
#+end_src
**** Save system admin password
#+begin_src yaml
- name: core | kanidm setup | save system admin password to root home directory
  ansible.builtin.copy:
    content: >-
      {{ (kanidm_sys_admin_recovery.stdout | split('new_password: "'))[1] | replace('"', '') | trim }}
    dest: /root/kanidm_admin_password.txt
    mode: '0600'
  when: not admin_recovered.stat.exists
#+end_src
**** Mark admin password as recovered
#+begin_src yaml
- name: core | kanidm setup | mark admin password as recovered
  ansible.builtin.file:
    path: /etc/kanidm/.admin_recovered
    state: touch
  when: not admin_recovered.stat.exists
  no_log: true
#+end_src
**** Authenticate CLI as admin
#+begin_src yaml
- name: core | kanidm setup | authenticate CLI as system admin
  ansible.builtin.shell: "KANIDM_PASSWORD=$(cat /root/kanidm_admin_password.txt) kanidm login --name admin"
  changed_when: false
#+end_src
*** Recover Default idm_admin Account
Kanidm separates global configuration (admin) from user management (idm_admin).
**** Check if idm_admin password was recovered
#+begin_src yaml
- name: core | kanidm setup | check if idm_admin password was already recovered
  ansible.builtin.stat:
    path: /etc/kanidm/.idm_admin_recovered
  register: idm_admin_recovered
#+end_src
**** Recover idm_admin password
#+begin_src yaml
- name: core | kanidm setup | recover idm_admin password
  ansible.builtin.command: kanidmd recover-account -c /etc/kanidm/server.toml idm_admin
  register: kanidm_idm_admin_recovery
  when: not idm_admin_recovered.stat.exists
#+end_src
**** Save idm_admin password
#+begin_src yaml
- name: core | kanidm setup | save idm_admin password to root home directory
  ansible.builtin.copy:
    content: >-
      {{ (kanidm_idm_admin_recovery.stdout | split('new_password: "'))[1] | replace('"', '') | trim }}
    dest: /root/kanidm_idm_admin_password.txt
    mode: '0600'
  when: not idm_admin_recovered.stat.exists
#+end_src
* Handlers
** Main
#+begin_src conf :tangle handlers/main.yml
---
- name: core | kanidm setup | restart systemd service
  ansible.builtin.systemd:
    name: kanidmd
    state: restarted
    daemon_reload: true
#+end_src
* Vars
** Main
#+begin_src yaml :tangle vars/main.yml
---
#kanidm_unixd_token: <variable in ansible-vault>
kanidm_domain: kanidm.internal
kanidm_origin: https://kanidm.internal
kanidm_headscale_oidc_callback: https://andira.lbic.fee.unicamp.br/oidc/callback
kanidm_ip: 10.10.20.5
#+end_src
* Templates
** server.toml.j2
#+begin_src conf :tangle templates/server.toml.j2
version = "2"
bindaddress = "0.0.0.0:443"
ldapbindaddress = "0.0.0.0:636"
origin =  "{{ kanidm_origin }}"
domain = "{{ kanidm_domain }}"
db_path = "/var/lib/kanidmd/kanidm.db"
tls_chain = "/etc/kanidm/chain.pem"
tls_key = "/etc/kanidm/key.pem"
#+end_src
