---
- name: ops | offboard | authenticate CLI as idm_admin
  ansible.builtin.shell: "KANIDM_PASSWORD=$(cat /root/kanidm_idm_admin_password.txt) kanidm login --name idm_admin"
  changed_when: false
  no_log: true
