---
- name: ops | workstations | authenticate CLI as idm_admin
  ansible.builtin.shell: "KANIDM_PASSWORD=$(cat /root/kanidm_idm_admin_password.txt) kanidm login --name idm_admin"
  changed_when: false
  no_log: true

- name: ops | workstations | create workstation users group
  ansible.builtin.command: kanidm group create {{ item.hostname }}_users --name idm_admin
  loop: "{{ workstations }}"
  register: kanidm_ws_users_create
  changed_when:
    - kanidm_ws_users_create.rc == 0
    - "'already' not in kanidm_ws_users_create.stdout | lower"
    - "'already' not in kanidm_ws_users_create.stderr | lower"
  failed_when:
    - kanidm_ws_users_create.rc != 0
    - "'already exists' not in kanidm_ws_users_create.stderr | lower"
    - "'409' not in kanidm_ws_users_create.stderr"

- name: ops | workstations | create workstation admins group
  ansible.builtin.command: kanidm group create {{ item.hostname }}_admins --name idm_admin
  loop: "{{ workstations }}"
  register: kanidm_ws_admins_create
  changed_when:
    - kanidm_ws_admins_create.rc == 0
    - "'already' not in kanidm_ws_admins_create.stdout | lower"
    - "'already' not in kanidm_ws_admins_create.stderr | lower"
  failed_when:
    - kanidm_ws_admins_create.rc != 0
    - "'already exists' not in kanidm_ws_admins_create.stderr | lower"
    - "'409' not in kanidm_ws_admins_create.stderr"
